### ISSUE TITLE
non alphanumeric node types

### ISSUE THREAD

**Issue by cancerberoSgx** [tree-sitter/tree-sitter-rust#39]
I'm pretty new with rust but I have plenty experience with other languages AST and I'm noticing that, if I iterate descendants **directly using children property**, for the following code:

```rust
pub type __darwin_size_t = ::std::os::raw::c_ulong;
```

The following ast is generated:

```json
{"type":"source_file","children":[{"type":"type_item","children":[
  {"type":"visibility_modifier","children":
    [{"type":"pub"}]},{"type":"type"},{"type":"type_identifier"},{"type":"="},{"type":"scoped_type_identifier","children":[{"type":"scoped_identifier","children": 
 [{"type":"scoped_identifier","children":[{"type":"scoped_identifier","children":
    [{"type":"::"},{"type":"identifier"}]},{"type":"::"},{"type":"identifier"}]},{"type":"::"},
    {"type":"identifier"}]},{"type":"::"},{"type":"type_identifier"}]},{"type":";"}]}]}
```

And as you can notice there are node for which their types are are ':', '=', '::', ';'

Is this OK? I read that a convention is to ignore types starting with underscore, so in this case is not clear if I should ignore or is an issue.

IMO these nodes are not ignorable since they add important semantics to the program and  I would be loosing information or if not I think without these it will be harder to figure it out.

Again, I'm completely new in rust syntax but in other language they tend to name these kind of node Tokens, like ColonToken. In TypeScript there is even one called "DotDotDotToken" or "OpenTagGreaterThanToken". 

Thanks, and sorry if I'm completely wrong about this and is not an issue at all, great project!

**Comment by maxbrunsfeld** [comment]
> there are nodes for which their types are ':', '=', '::', ';'
>
> Is this OK?

Yeah, that's the expected behavior. A token with `type: "::"` represents (as you might guess) the `::` token. This [section of the docs](http://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes) might be helpful.

In particular, nodes have a property called `named` that indicates whether they were given a *name* in the grammar or not. Most often, nodes that represent simple tokens like `::` are *not* named, and their `type` property corresponds directly to their string value.

> Is this OK? I read that a convention is to ignore types starting with underscore,

That concept isn't relevant to you if you're *using* a parser. That's an API when you're *defining* a grammar: you can mark named rules as *private* if you prefix their names with an underscore. Then they will not show up in the tree at all.

An example of that is the [`_declaration_statement`](https://github.com/tree-sitter/tree-sitter-rust/blob/06b206825671f78f566913083bc09903a8b197de/grammar.js#L87) rule in the Rust grammar. It is used in the grammar for grouping and parsing purposes, but notice that you did not see it in your syntax tree. Does that make sense?

**Comment by cancerberoSgx** [comment]
> An example of that is the [`_declaration_statement`](https://github.com/tree-sitter/tree-sitter-rust/blob/06b206825671f78f566913083bc09903a8b197de/grammar.js#L87) rule in the Rust grammar. It is used in the grammar for grouping and parsing purposes, but notice that you did not see it in your syntax tree. Does that make sense?

Yes it does, and is more comfortable than long syntax kind names. Sorry I mess that in the docs and 
 . Now I'm seeing seeing the same pattern in other  languages. 

Recently I was playing a lot with antlr4 and ported to  JS and normalized the output of node visitors to build ASTs. This is WIL (just a couple of weeks old, but has many languages  "AST parsers":

https://cancerberosgx.github.io/demos/univac/playground/

As you said in the docs, I had to post process the output given by node visitors (which is the only way to extract something similar to an AST) and remove nodes matched by auxiliary grammar rules[0]

Grammars were taken from antlr4 grammars project https://github.com/antlr/grammars-v4 . I think that, although those are not designed to generate AST, it could be very helpful for a first approximation. Some of them are taken from official projects / compilers / interpreters and don't need much post processing to deliver an acceptable AST or at least good starting points for new parsers.

Will play a bit more with this library and see if something is missing here that I can contribute with. I think grammars for R and smalltalk are official.

BTW, I wonder if this project has any preference on languages? For example, antlrs  have grammars for things like assembler, makefiles, UTF, unicode, sass, less, and very old languages like logo, basic, fortran. cobol, or things like SQL/graphQl...

Thank you !

[0]  --  [see redundantTypes have the types I removed for each lang](https://github.com/cancerberoSgx/univac/blob/6b166b30ecf4a6c8e4de1a0e9f29da32675a8ff4/src/parserImpl.ts#L78)
