### ISSUE TITLE
"&" inside a macro isn't recognized

### ISSUE THREAD

**Issue by stsewd** [tree-sitter/tree-sitter-rust#98]
```rust
println!("{}", &foo);
```

Here the query `"&" @operator` doesn't match the `&`, if the macro is changed for a function call it works

```rust
println("{}", &foo);
```

**Comment by resolritter** [comment]
I think this could relate to https://github.com/tree-sitter/tree-sitter-rust/pull/96.

This could be more broadly described as "individual tokens are not designated inside of `token_tree`" since other valid operators, such as `^`, are also not designated inside of them. They are indeed not currently queryable inside of `token_tree`s

https://github.com/tree-sitter/tree-sitter-rust/blob/2beedf23bedbd7b02b416518693e8eed3944d4a0/grammar.js#L190-L193

@maxbrunsfeld @ninevra what do you think of this in light of the ideas in #96? Are those concerns relatable? Also should those tokens be queryable inside of `token_tree`?

**Comment by brozi** [comment]
Hi. I'm experiencing what I think is a related issue:
With
```
println!("{}", var1 + var2);
```
the "," and "+" are not in the ast.
